# Seed for LHS sampling
seed: 42

# Cost parameters
q: [1]
r: [0.1]

#Prior model args
custom_prior_dynamics : False
learn_op: False


# GP training args
train_samples: 500
validation_samples: 200
train_iterations: [1000]
learning_rate: [0.1]
use_gpu: False
gp_model_path: null

#H2 optimization args
step_size: 0.1
max_optim_tries: 100


# Runner args
deque_size: 10
eval_batch_size: 1
output_dir: "./results/gprc_baseline/"
# Plot
plot_traj: False
save_plot: True
plot_dir: "./results/gprc_baseline/"
# Export csv files
save_data: True
data_dir: "./results/lgprc_baseline/"